# Generated by Django 4.0.5 on 2022-07-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elif', '0002_order_alter_food_options_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
